"""rename telefono to phone in contacts

Revision ID: b10dff21436a
Revises: 992a6d5ab512
Create Date: 2026-07-22 19:51:14.931217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10dff21436a'
down_revision: Union[str, Sequence[str], None] = '992a6d5ab512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone', sa.String(length=50), nullable=True))
    op.drop_column('contacts', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'phone')
    # ### end Alembic commands ###
